Nice path decomposition was made
tunyash/disj_paths_bd_tw pull request #2
Opened 2021-06-27 10:00 UTC by bazillo

2021-06-27 10:35 UTC, tunyash requested changes
Please add a niceness check method and address the comments (as well as the failing unit test check)

2021-06-27 10:35 UTC, tunyash commented on CMakeLists.txt
> +add_executable(nice_test src/nice-path-decomposition/test.cpp)
Let's put the class and the test file in the root of src.

2021-06-27 10:35 UTC, tunyash commented on src/nice-path-decomposition/test.cpp
> +    auto nice_a = p.get_nice_bags();
Does it checks the correctness? Seems like the correctness of the nice representation is never checked. Please add a method for it.

2021-06-27 10:35 UTC, tunyash commented on src/nice-path-decomposition/nice-path-decomposition.cpp
> +void NicePathDecomposition::nice_transform() {
Does it change the initial _bags field? The word 'transform' suggest so.

2021-06-27 10:35 UTC, tunyash commented on src/nice-path-decomposition/nice-path-decomposition.h
> +    NicePathDecomposition(std::vector<std::vector<vertex_t>> &bags, Graph &g);
Add docstrings for constructors and public methods. Make sure you mention that the bags here are not expected to be nice.

2021-06-27 10:35 UTC, tunyash commented on src/nice-path-decomposition/nice-path-decomposition.h
> +class NicePathDecomposition : public PathDecomposition {
Add a docstring: a definition of a nice path decomposition and the purpose of this class.

2021-06-27 10:35 UTC, tunyash commented on src/nice-path-decomposition/test.cpp
> +//#include "../centroid-tree.h"
Remove

2021-06-27 10:35 UTC, tunyash commented on src/nice-path-decomposition/nice-path-decomposition.cpp
> +        for (int i = 0; i < prev_bag.size(); i++) {
This is a for loop over a changing vector that manipulates i inside the loop. This makes code harder to read and more bug-prone than necessary. Here you compute the difference between the set of nodes in the current bag and in the next one. There is a function in the STD algorithm library that does that.

2021-06-27 10:35 UTC, tunyash commented on src/nice-path-decomposition/nice-path-decomposition.cpp
> +        for (vertex_t v : vertices) {
Here you need to iterate over difference between current bag and the previous one which also can be done via the standard function

2021-06-27 15:49 UTC, tunyash approved these changes
LGTM, given the comments are addressed

2021-06-27 15:49 UTC, tunyash commented on src/nice-path-decomposition.cpp
> +            std::cerr << "vertex " << v << " haven't been added";
throw Exception instead (and in all the remaining places as well)

2021-06-27 15:49 UTC, tunyash commented on src/nice-path-decomposition.cpp
> +bool NicePathDecomposition::Bag::operator<(Bag b) {
I don't quite get what is it for, is it just to have some comparator or does it have a more sophisticated purpose? If it is just to be able to use sets, I suggest simply joining all fields into a tuple and comparing the tuples.

2021-06-27 15:49 UTC, tunyash commented on src/nice-path-decomposition.h
> +    NicePathDecomposition(std::vector<std::vector<vertex_t>> &bags, Graph &g);
should bags be const?

2021-06-27 19:09 UTC, elproblema commented
Is it possible to cast NicePathDecomposition to PathDecomposition?

2021-06-27 19:59 UTC, elproblema commented
unit-tests.yml has to run successfully

2021-06-28 08:21 UTC, merged

2021-06-28 09:06 UTC, elproblema commented on CMakeLists.txt
> +target_link_libraries(nice_test PUBLIC nice_path_dec path_dec centroid_tree)
I suppose its better to add nice-test.cpp to test executable. As well for unit-tests.yml

2021-06-28 09:06 UTC, elproblema commented on .github/workflows/unit-tests.yml
> +          ./test
Delete ./nice_test

2021-06-28 09:06 UTC, elproblema commented on src/centroid-tree.cpp
> +    treedec::exact_decomposition_cutset(temp, t);
Add a new issue about it

2021-06-28 09:06 UTC, elproblema commented on src/nice-path-decomposition.cpp
> +    return _nice_bags;
Should be const &

2021-06-28 09:06 UTC, elproblema commented on src/nice-path-decomposition.cpp
> +    std::vector<int> left(n, n + 1);
Make variables names the same as for path-decomposition.h

2021-06-28 09:06 UTC, elproblema commented on src/nice-path-decomposition.h
> +        The porpoise of using it is that it will help to calculate the dynamic.
Lexical error in docstring

2021-06-28 09:06 UTC, elproblema commented on src/nice-path-decomposition.cpp
> +    return (v1 < v2) || (v1 == v2 && type == ADD_VERTEX);
In your operator sometimes commutativity is allowed, which might cause errors